a=int(input("Geben Sie bitte Zahl A ein: "))
b=int(input("Geben Sie bitte Zahl B ein: "))
c=int(input("Geben Sie bitte Zahl C ein: "))
d=min(a,b,c)
print("Das Minimum von", a, "und", b, "und", c, "ist", d, sep=" ", end="%")
print("Hallo")
